<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>1602</X>
  <Y>342</Y>
  <VerticalWidth>312</VerticalWidth>
  <VerticalHeight>490</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF1A1A1A</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>24FFFFFF</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF00CC36</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF52CC73</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC5C52</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC1200</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FFACACAC</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABFTZWdvZSBVSSBTZW1pYm9sZAAAMEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxIZW1pIEhlYWQgUmdWVQVCBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxIZW1pIEhlYWQgUmcAACBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>False</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>SolidColor</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>False</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7.3</Version>
        <ShowGameName>True</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>True</ShowAttemptCount>
        <ShowFinishedRunsCount>True</ShowFinishedRunsCount>
        <OverrideTitleFont>False</OverrideTitleFont>
        <OverrideTitleColor>False</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TitleFont>
        <SingleLine>False</SingleLine>
        <TitleColor>FFFFFFFF</TitleColor>
        <BackgroundColor>00000000</BackgroundColor>
        <BackgroundColor2>FF131313</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DisplayGameIcon>True</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>True</ShowVariables>
        <TextAlignment>1</TextAlignment>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Splits.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <CurrentSplitTopColor>FF005717</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF153574</CurrentSplitBottomColor>
        <VisualSplitCount>7</VisualSplitCount>
        <SplitPreviewCount>0</SplitPreviewCount>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>True</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Hundredths</SplitTimesAccuracy>
        <AutomaticAbbreviations>False</AutomaticAbbreviations>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <ShowBlankSplits>True</ShowBlankSplits>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>24</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>0</SplitHeight>
        <CurrentSplitGradient>Plain</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>01FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <SeparatorLastSplit>False</SeparatorLastSplit>
        <DeltasAccuracy>Hundredths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <Display2Rows>False</Display2Rows>
        <ShowColumnLabels>False</ShowColumnLabels>
        <LabelsColor>FFFFFFFF</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>+/-</Name>
            <Type>Delta</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Game Time</TimingMethod>
          </Settings>
          <Settings>
            <Version>1.5</Version>
            <Name>Time</Name>
            <Type>SplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Game Time</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.DetailedTimer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <Height>75</Height>
        <Width>200</Width>
        <SegmentTimerSizeRatio>40</SegmentTimerSizeRatio>
        <TimerShowGradient>True</TimerShowGradient>
        <OverrideTimerColors>False</OverrideTimerColors>
        <SegmentTimerShowGradient>True</SegmentTimerShowGradient>
        <TimerFormat>00:01.23</TimerFormat>
        <SegmentTimerFormat>00:01.23</SegmentTimerFormat>
        <SegmentTimesAccuracy>Hundredths</SegmentTimesAccuracy>
        <TimerColor>FFAAAAAA</TimerColor>
        <SegmentTimerColor>FFAAAAAA</SegmentTimerColor>
        <SegmentLabelsColor>FFFFFFFF</SegmentLabelsColor>
        <SegmentTimesColor>FFFFFFFF</SegmentTimesColor>
        <SegmentLabelsFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxIZW1pIEhlYWQgUmcAACBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></SegmentLabelsFont>
        <SegmentTimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxIZW1pIEhlYWQgUmcAACBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></SegmentTimesFont>
        <SplitNameFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAMEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SplitNameFont>
        <DisplayIcon>False</DisplayIcon>
        <IconSize>40</IconSize>
        <ShowSplitName>False</ShowSplitName>
        <SplitNameColor>FFFFFFFF</SplitNameColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Comparison2>Best Segments</Comparison2>
        <HideComparison>False</HideComparison>
        <TimingMethod>Game Time</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
        <SegmentTimerDecimalsSize>35</SegmentTimerDecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.DetailedTimer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <Height>75</Height>
        <Width>200</Width>
        <SegmentTimerSizeRatio>40</SegmentTimerSizeRatio>
        <TimerShowGradient>True</TimerShowGradient>
        <OverrideTimerColors>False</OverrideTimerColors>
        <SegmentTimerShowGradient>True</SegmentTimerShowGradient>
        <TimerFormat>00:01.23</TimerFormat>
        <SegmentTimerFormat>00:01.23</SegmentTimerFormat>
        <SegmentTimesAccuracy>Hundredths</SegmentTimesAccuracy>
        <TimerColor>FFAAAAAA</TimerColor>
        <SegmentTimerColor>FFAAAAAA</SegmentTimerColor>
        <SegmentLabelsColor>FFFFFFFF</SegmentLabelsColor>
        <SegmentTimesColor>FFFFFFFF</SegmentTimesColor>
        <SegmentLabelsFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxIZW1pIEhlYWQgUmcAACBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></SegmentLabelsFont>
        <SegmentTimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAxIZW1pIEhlYWQgUmcAACBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAMAAAAL]]></SegmentTimesFont>
        <SplitNameFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAMEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SplitNameFont>
        <DisplayIcon>False</DisplayIcon>
        <IconSize>40</IconSize>
        <ShowSplitName>False</ShowSplitName>
        <SplitNameColor>FFFFFFFF</SplitNameColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Comparison2>Best Segments</Comparison2>
        <HideComparison>False</HideComparison>
        <TimingMethod>Real Time</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
        <SegmentTimerDecimalsSize>35</SegmentTimerDecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.MemoryGraph.dll</Path>
      <Settings>
        <Version>1.5.2.0</Version>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <GraphColors>
        </GraphColors>
        <MinimumValue>0</MinimumValue>
        <MaximumValue>3500</MaximumValue>
        <GraphWidth>110</GraphWidth>
        <GraphHeight>30</GraphHeight>
        <HorizontalMargins>0</HorizontalMargins>
        <VerticalMargins>0</VerticalMargins>
        <GraphStyle>FilledGraph</GraphStyle>
        <BackgroundGradient>Plain</BackgroundGradient>
        <GraphGradient>Plain</GraphGradient>
        <GraphSillyColors>False</GraphSillyColors>
        <ValueTextPosition>Right</ValueTextPosition>
        <DescriptiveTextPosition>Left</DescriptiveTextPosition>
        <LocalMax>False</LocalMax>
        <ProcessName>RoboQuest-Win64-Shipping</ProcessName>
        <DescriptiveText>Speed</DescriptiveText>
        <SelectedGame>Roboquest (0.8.9)</SelectedGame>
        <SelectedGameOption>
        </SelectedGameOption>
        <Module>
        </Module>
        <Base>04B427F0</Base>
        <Offsets>180,38,0,30,260,46A0</Offsets>
        <ValueType>Float</ValueType>
        <DescriptiveTextColor>00000000</DescriptiveTextColor>
        <DescriptiveTextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></DescriptiveTextFont>
        <DescriptiveTextOverrideColor>False</DescriptiveTextOverrideColor>
        <DescriptiveTextOverrideFont>False</DescriptiveTextOverrideFont>
        <ValueTextColor>00000000</ValueTextColor>
        <ValueTextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></ValueTextFont>
        <ValueTextOverrideColor>False</ValueTextOverrideColor>
        <ValueTextOverrideFont>False</ValueTextOverrideFont>
        <ValueTextDecimals>2</ValueTextDecimals>
        <UnitConversionEnabled>False</UnitConversionEnabled>
        <UnitsUsed>None</UnitsUsed>
        <MeterInGameUnits>1</MeterInGameUnits>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.ScriptableAutoSplit.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <ScriptPath>C:\REPLACE\WITH\PATH\TO\roboquest.asl</ScriptPath>
        <Start>True</Start>
        <Reset>True</Reset>
        <Split>True</Split>
        <CustomSettings>
          <Setting id="reset-death" type="bool">False</Setting>
          <Setting id="reset-game" type="bool">True</Setting>
        </CustomSettings>
      </Settings>
    </Component>
  </Components>
</Layout>